version: '3.7'

services:
  executor-runner:
    image: daturaai/compute-subnet-executor-runner:latest
    pull_policy: never
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "$HOME/.bittensor/wallets:/root/.bittensor/wallets"
      - ./.env:/root/executor/.env
      - /root/compute-subnet/neurons/executor/src:/root/executor/src:ro
      - ./executor-compose.yml:/root/executor/docker-compose.yml
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:1.7.1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --label-enable